### ISSUE TITLE
Run purgecss in gatsby develop mode

### ISSUE THREAD

**Issue by ZoltanVeres** [anantoghosh/gatsby-plugin-purgecss#119]
**Is your feature request related to a problem? Please describe.**
I noticed that purge-css is only running during on `gatsby build`. It would be really awesome to have the possibility to run this using `gatsby develop`. It may be extremely complicated to implement, but maybe i'm missing something here

**Describe the solution you'd like**
If a change is happening the code during running the `gatsby develop`, gatsby picks up that change and reloads the page in the browser.It would be really nice if purgecss could run before the site is delivered

**Describe alternatives you've considered**

**Additional context**
Please close this issue if this is already implemented, i was not seeing any sign in the code for this, but again, maybe i'm missing something

**Comment by anantoghosh** [comment]
@ZoltanVeres Sorry for the late response.
Purging when developing is now available in v3.
Use the `develop: true` option. It won't show the total css removed. Use `printRejected: true` option to see what selectors are being removed.
