### ISSUE TITLE
Remove css classes that are not present in the rendered html file

### ISSUE THREAD

**Issue by ThisNameWasTaken** [anantoghosh/gatsby-plugin-purgecss#175]
Let's say that we have the fallowing code
```js
import React from 'react'
import classnames from 'classnames'
import '@material/button/mdc-button.scss'

const Button = ({ raised, unelevated, outlined, dense, className, children }) => (
  <button
    className={classnames('mdc-button', className, {
      'mdc-button--raised': raised,
      'mdc-button--unelevated': unelevated,
      'mdc-button--outlined': outlined,
      'mdc-button--dense': dense
    })}
  >
    {children}
  </button>
)

export default Button
```

**Expected behavior**
If in my app I only use `<Button>` and `<Button raised>`, `mdc-button` and `mdc-button--raised` should be kept, but `mdc-button--unelevated`, `mdc-button--outlined` and `mdc-button--dense` should be discarded.

**Current behavior**
All css classes mentioned above are kept.

**Possible solution**
Use the server side rendered html to determine exactly what css classes are being used and which are not. Inside `gatsby-ssr.js` you can get the html, but I do not know how to get the css.

If it helps here is a snippet that would get the body component of the html .
```js
const { renderToString } = require('react-dom/server');

exports.replaceRenderer = ({ bodyComponent }) => {
  const bodyHTML = renderToString(bodyComponent);
}
```

**Comment by anantoghosh** [comment]
Purgecss looks at the script file contents for selector names, so all selectors are preserved as it should.
If rest of the selectors are purged, then dynamically changing selectors will not work, for eg: changing the button from raised to dense by passing new props.

If you need to improve purging behaviour, look at purgecss's extractor option https://github.com/FullHuman/purgecss-docs/blob/master/extractors.md.
