### ISSUE TITLE
how to whitelist a Loadable component ?

### ISSUE THREAD

**Issue by deebov** [anantoghosh/gatsby-plugin-purgecss#484]
I am using a Loadable component. That components has some elements that use css selectors. But as this component is Loadable `gatsby-plugin-purgecss` removes the selectors inside that component.

Is there a way to solve this issue ?

**Comment by anantoghosh** [comment]
Where are the styles and the component's source defined (relative file path)?

**Comment by deebov** [comment]
So I have imported a one css file in a Layout component. That's an icon system css file.

**Comment by anantoghosh** [comment]
There is not enough info for me to help you directly, so I'll give the general tips.
Use the `printRejected` option to find the files and selectors which were purged, then whitelist the whole file or just the selectors.
If your component is from a npm package, then see [this](https://github.com/anantoghosh/gatsby-plugin-purgecss#issue-5-using-npm-packages-with-components-which-import-css-files).
Being loadable does not have any impact on the purging behavior as it only compares css with script's source.
