### ISSUE TITLE
Remove css classes from a theme

### ISSUE THREAD

**Issue by alexluong** [anantoghosh/gatsby-plugin-purgecss#546]
**Is your feature request related to a problem? Please describe.**
`purgecss` will purge all classes from themes (other than the current project directory).

For example, a theme can have a file `ArticleTemplate.js` that includes Tailwind classes. These classes will be purged by `gatsby-plugin-purgecss`.

**Describe the solution you'd like**
`gatsby-plugin-purgecss` will recursively check all Gatsby themes/plugins before purging css.

This would provide the best user experience as well as the expected behavior as Gatsby themes are going to be a big part of Gatsby in the future.

**Describe alternatives you've considered**
When registering `gatsby-plugin-purgecss`, I think an extra option of `include` can be helpful. Something like this:

```js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-purgecss",
      options: {
        include: [require("my-gatsby-theme-1"), require("my-gatsby-theme-2")]
      }
    }
  ]
}
```

With this, `purgecss` will also check these directory before purging the classes.

**Comment by anantoghosh** [comment]
Hi @alexluong, there is already the `content` option for this https://github.com/anantoghosh/gatsby-plugin-purgecss#issue-5-using-npm-packages-with-components-which-import-css-files

**Comment by andrewfairlie** [comment]
@alexluong did you ever get a working solution to this? Using the `content` option feels a little un-Gatsby'ish to me.
