### ISSUE TITLE
Option to run against rendered html

### ISSUE THREAD

**Issue by dangayle** [anantoghosh/gatsby-plugin-purgecss#567]
There was [a previous ticket](https://github.com/anantoghosh/gatsby-plugin-purgecss/issues/175) that was similar, but not was closed because it had a slightly different problem.

I want Purgecss to run run against the rendered html, not against the jsx components. I have a CMS that sends classes from a color swatch picker. I don't want to whitelist all of them, my css file can go from 40kb up to 2020kb.

Having the option to parse the final rendered html instead would make this easy, but I'm guessing the final html isn't ready at the point the css file is being prepared?

**Comment by anantoghosh** [comment]
Yes this plugin works before the html is rendered.
I think it would be better to have a separate plugin which could remove css post build, https://github.com/youfoundron/gatsby-plugin-purify-css used this approach but is not maintained anymore.
You could also try running purgecss separately on the built html, you'll have to extract the css from the html to do so.
