### ISSUE TITLE
classes added by clsx not in css

### ISSUE THREAD

**Issue by gijsbotje** [anantoghosh/gatsby-plugin-purgecss#670]
Hee there,

 i'm trying to use [clsx](https://github.com/lukeed/clsx#readme) to do some logic for dynamicly building the classes based on the props of a component. The classes are all bootstrap classes that are added and formed by clsx. 
am i correct in assuming purgecss only reads the actually added names in `className` attributes in the js files? and not also the dynamically created ones inside a component or using clsx?

i currently have a button component like this
```
import React from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';

const Button = ({ color, outline, size, component, href, children, className, ...rest }) => {
  const Component = component || href !== undefined ? 'a' : 'button';

  return (
    <Component
      href={href}
      className={clsx(
        'btn',
        {
          [`btn-${outline ? 'outline-' : ''}${color}`]: color,
          [`btn-${size}`]: ['sm', 'lg'].includes(size),
        },
        className,
      )}
      {...rest}
    >
      {children}
    </Component>
  );
};

Button.propTypes = {
  children: PropTypes.any.isRequired,
  className: PropTypes.string,
  color: PropTypes.oneOf(['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'light', 'link']),
  component: PropTypes.any,
  href: PropTypes.string,
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
  outline: PropTypes.bool,
};

Button.defaultProps = {
  className: undefined,
  color: 'primary',
  component: undefined,
  href: undefined,
  size: 'md',
  outline: false,
};

export default Button;

```

when i use this in a page component like this
```
<Button size="lg" color="secondary" type="button">
  click me
</Button>
```
it purges all button classes defined by bootstrap. Is there a way of fixing this without the need to whitelist everything that breaks?

**Comment by anantoghosh** [comment]
PurgeCss matches words in the source files to get the selectors before any execution, therefore it cannot match variables to the actual classes.
Unfortunately I don't see any simple way to make it work without whitelisting the classes.
Instead of using `whitelist`, you could add the classes in the comments in the same file and they would be kept.

Maybe you _could_ run purgecss directly by extracting the css from the generated html files.

**Comment by gijsbotje** [comment]
hmm that's a pity, it kind of needs to do all classes as the js might change some classes in the future. And whitelisting will be a pain to keep up to date. Guess it won't work for our use case then.
thanks for the quick response!
