### ISSUE TITLE
How to specify custom tailwind config file?

### ISSUE THREAD

**Issue by jasonlimantoro** [anantoghosh/gatsby-plugin-purgecss#744]
It seems that the warning

```
Tailwind is not purging unused styles because no template paths have been provided.
If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
removing unused styles, set `purge: false` in your Tailwind config file to silence
this warning.
```
keeps coming when running `gatsby build`.
Not sure how to provide the template path.

**Comment by anantoghosh** [comment]
tailwind >1.4 has added purging, thus `gatsby-plugin-purgecss` may not be needed for tailwind.
Please follow the tailwind guide on how to set up purging https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css.

**Comment by jasonlimantoro** [comment]
I just realized that. Thank you for the quick reply!
Maybe should update the README for future users to know.
Thank you!
