### ISSUE TITLE
Disable print with the tailwind option

### ISSUE THREAD

**Issue by MatteoGauthier** [anantoghosh/gatsby-plugin-purgecss#849]
**Is your feature request related to a problem? Please describe.**
The plugin log a lot of content, logging service have a log size.

**Describe the solution you'd like**
A simpler option used to disable large printing in console

**Comment by anantoghosh** [comment]
The default behavior of this plugin is to only print the size difference.
Setting the `printRejected` option to true prints the removed selectors.
You just need to remove it.

**Comment by MatteoGauthier** [comment]
| Options                                | Print ? |
| -------------------------------------- | ------- |
| `no options`                           | yes     |
| `tailwind: true`                       | yes     |
| `tailwind: false`                      | yes     |
| `printRejected: true`                  | yes     |
| `printRejected: false`                 | yes     |
| `rejected: false`                      | yes     |
| `rejected: true`                       | yes     |
| `tailwind: true, rejected: false`      | yes     |
| `tailwind: true, rejected: true`       | yes     |
| `tailwind: true, printRejected: false` | yes     |
| `tailwind: true, printRejected: true`  | yes     |

**Comment by anantoghosh** [comment]
Can you check if tailwind's own purgecss is enabled and printing that? Try disabling this plugin and see if output changes.

**Comment by MatteoGauthier** [comment]
I tried as well

Le lun. 10 août 2020 à 07:11, Ananto Ghosh <notifications@github.com> a
écrit :

**Comment by anantoghosh** [comment]
If you provide a repo I could look into it.
