### ISSUE TITLE
Not understanding how to configure content option. Documentation unclear

### ISSUE THREAD

**Issue by spk2dc** [anantoghosh/gatsby-plugin-purgecss#896]
**Verify if it is a postcss bug**
First verify that gatsby-plugin-purgecss is working by setting the option `printRejected: true` which will print out the list of removed selectors.
If the plugin is working, but the css is not getting purged as you would have hoped then it's very likely a purgecss issue. File for purgecss related bugs here https://github.com/FullHuman/purgecss/issues.

- [x] **I have verified that this is not a purgecss issue.**

**Describe the bug**
Please provide clearer documentation on the content option. I have read through the section on it and googled regex patterns but cannot quite understand what the snippet of code below is doing or how it works. I need to modify this so that css from npm packages like bootstrap is not removed from my site, but cannot figure out how to change this code to get that to work and what each part of the code means. It would be very helpful if you dissected the code and provided explanations of each part, for example what /**/ does, what (*.d) does, what {ts,js} does, etc. 

content: [
  path.join(process.cwd(), 'src/**/!(*.d).{ts,js,jsx,tsx}'),
  path.join(process.cwd(), 'anotherFolder/!(*.d).{ts,js,jsx,tsx}')
];

**To Reproduce**
Add npm packages such as bootstrap to a site that uses purgecss and it will not work correctly because the css in the package will be removed.

**Configs**
content: [
  path.join(process.cwd(), 'src/**/!(*.d).{ts,js,jsx,tsx}'),
  path.join(process.cwd(), 'anotherFolder/!(*.d).{ts,js,jsx,tsx}')
];
Please remove any personal information present in the files.
- [x] **I have removed all personal information.**

**Expected behavior**
CSS from bootstrap and other npm packages is not purged

**Additional information**
N/A

**Comment by anantoghosh** [comment]
The content option is from purgecss directly. You can read more about it here https://purgecss.com/configuration.html#options.
> I have read through the section on it and googled regex patterns

The pattern there is not regex, it's glob https://en.wikipedia.org/wiki/Glob_(programming).

`src/**/!(.d).{ts,js,jsx,tsx}` simply means find all files recursively in `src` which end in .ts, .js, .jsx or .tsx *except* .d.ts files.

To include a folder under node modules in content options, follow point 3 in https://github.com/anantoghosh/gatsby-plugin-purgecss#issue-5-using-npm-packages-with-components-which-import-css-files

**Comment by spk2dc** [comment]
Thanks for that detailed answer, it helped me fix my problem! Would be good to add this information to the readme for anyone else that didn't know about glob or how the provided sample code worked.
