### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by RebootGG** [anantoghosh/gatsby-plugin-purgecss#944]
Hi, 

Would you consider adding support for TypeScript ? 

I have this message when I'm trying to use the plugin in a .tsx file : 

`TS7016: Could not find a declaration file for module 'gatsby-plugin-breadcrumb/'. '****/node_modules/gatsby-plugin-breadcrumb/index.js' implicitly has an 'any' type.   Try 'npm i --save-dev @types/gatsby-plugin-breadcrumb' if it exists or add a new declaration (.d.ts) file containing 'declare module 'gatsby-plugin-breadcrumb/';'` 

Thanks

**Comment by anantoghosh** [comment]
@RebootGG wrong project. I think you are looking for https://github.com/sbardian/gatsby-plugin-breadcrumb.

**Comment by RebootGG** [comment]
Indeed, sorry about that.
