### ISSUE TITLE
purgeCSSOptions.content override is not working

### ISSUE THREAD

**Issue by vnobis-univ** [anantoghosh/gatsby-plugin-purgecss#958]
- [x] **I have verified that this is not a purgecss issue.**

**Describe the bug**
Custom purgeCSSOptions.content override is not applied (because it always uses default value).

Line with bug - [permalink](https://github.com/anantoghosh/gatsby-plugin-purgecss/blob/e19ea2977b0d58ec88055bc97f5ea6938cfc6a18/src/loader.ts#L59)
```js
  void new Purgecss()
    .purge({
      ...options.purgeCSSOptions,
      css: [{ raw: source }],
      content: [path.src],
    })
```
`content: [path.src]` will always override same property from `options.purgeCSSOptions`

**To Reproduce**
Try to use purgeCSSOptions.content override.

**Expected behavior**
Custom purgeCSSOptions.content override is working.

**Comment by anantoghosh** [comment]
Thank you pointing that out, should be fixed in v6.0.2.
